__all__ = ["SKI_BRANDS", "SNOWBOARD_BRANDS", "BOOT_BRANDS", "BINDING_TYPES", "BINDING_BRANDS_BY_TYPE"]

SKI_BRANDS = [
    "Atomic",
    "Armada",
    "Augment",
    "Black Crows",
    "Black Diamond",
    "Blizzard",
    "Bomber",
    "Coalition Snow",
    "DPS",
    "Dynastar",
    "Elan",
    "Faction",
    "Fischer",
    "Folsom",
    "Head",
    "Icelantic",
    "J Skis",
    "K2",
    "Kästle",
    "Liberty",
    "Line",
    "Majesty",
    "Meier Skis",
    "Moment",
    "Movement",
    "Nordica",
    "ON3P",
    "Parlor",
    "Peak Skis",
    "Praxis",
    "Prior",
    "Renoun",
    "RMU",
    "Rossignol",
    "Salomon",
    "Scott",
    "Season Eqpt",
    "Stöckli",
    "Van Deer",
    "Voilé",
    "Volkl",
    "Völkl",
    "WNDR Alpine",
    "Zag",
    "Other",
]

SNOWBOARD_BRANDS = [
    "Burton",
    "Capita",
    "Jones",
    "K2",
    "Lib Tech",
    "Never Summer",
    "Nitro",
    "Ride",
    "Rome",
    "Salomon",
    "GNU",
    "Arbor",
    "Other",
]

BOOT_BRANDS = [
    "Atomic",
    "Dalbello",
    "Fischer",
    "Head",
    "Lange",
    "Nordica",
    "Rossignol",
    "Salomon",
    "Tecnica",
    "Burton",
    "ThirtyTwo",
    "Vans",
    "K2",
    "Ride",
    "Other",
]

BINDING_TYPES = [
    "Alpine / Downhill",
    "Touring / Backcountry",
    "Hybrid",
    "Telemark",
    "Snowboard",
    "Other",
]

BINDING_BRANDS_BY_TYPE = {
    "Alpine / Downhill": [
        "Marker",
        "Look",
        "Salomon",
        "Tyrolia",
        "Atomic",
        "Head",
        "Rossignol",
        "VIST",
        "Kästle",
        "Elan",
        "Fischer",
        "Nordica",
        "Armada",
        "Black Diamond",
        "Other",
    ],
    "Touring / Backcountry": [
        "Dynafit",
        "ATK",
        "Fritschi",
        "Plum",
        "Marker",
        "Salomon",
        "Atomic",
        "Black Diamond",
        "G3",
        "Kreuzspitze",
        "Ski Trab",
        "Movement",
        "Other",
    ],
    "Hybrid": [
        "Marker",
        "Salomon",
        "Atomic",
        "Look",
        "CAST",
        "Fritschi",
        "Tyrolia",
        "Other",
    ],
    "Telemark": [
        "22 Designs",
        "Rottefella",
        "Voilé",
        "Bishop",
        "Meidjo",
        "The M Equipment",
        "Other",
    ],
    "Snowboard": [
        "Burton",
        "Union",
        "NOW",
        "Rome",
        "Bent Metal",
        "Flux",
        "Ride",
        "Jones",
        "Nitro",
        "Salomon",
        "K2",
        "Arbor",
        "Spark R&D",
        "Nidecker",
        "Flow",
        "Bataleon",
        "Other",
    ],
    "Other": [
        "Other",
    ],
}
