"""Add expires_at to InviteToken

Revision ID: 218e2db34714
Revises: b257ce551764
Create Date: 2025-12-26 05:46:53.869450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218e2db34714'
down_revision = 'b257ce551764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
