"""add password_changed_at to user

Revision ID: 272f5f30536f
Revises: e2c32ab9d311
Create Date: 2026-04-17 08:27:13.004458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272f5f30536f'
down_revision = 'e2c32ab9d311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_changed_at')

    # ### end Alembic commands ###
