"""Add accommodation_status and accommodation_link to SkiTrip

Revision ID: 2dc398f493f6
Revises: 7284516ddc3c
Create Date: 2025-12-23 22:27:57.902734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc398f493f6'
down_revision = '7284516ddc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('accommodation_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.drop_column('accommodation_link')
        batch_op.drop_column('accommodation_status')

    # ### end Alembic commands ###
