"""Add trip_duration to SkiTrip

Revision ID: 311665898421
Revises: f5ac6c9d89ea
Create Date: 2025-12-19 00:10:21.280532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311665898421'
down_revision = 'f5ac6c9d89ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.alter_column('send_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('environment',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'dev'::character varying"))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('environment',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'dev'::character varying"))

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.alter_column('is_seeded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True)

    # Add trip_duration column as nullable first
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_duration', sa.String(length=20), nullable=True))
    
    # Backfill existing trips based on date calculation
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE ski_trip SET trip_duration = 
            CASE 
                WHEN start_date = end_date THEN 'day_trip'
                WHEN (end_date - start_date) = 1 THEN 'one_night'
                WHEN (end_date - start_date) = 2 THEN 'two_nights'
                ELSE 'three_plus_nights'
            END
        WHERE trip_duration IS NULL
    """))
    
    # Now set NOT NULL constraint
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.alter_column('trip_duration', nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lifecycle_stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
        batch_op.alter_column('is_seeded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('email_opt_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('email_transactional',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('email_social',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('email_digest',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_digest',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('email_social',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('email_transactional',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('email_opt_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('is_seeded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('lifecycle_stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))

    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.drop_column('trip_duration')

    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.alter_column('is_seeded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('environment',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'dev'::character varying"))

    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.alter_column('environment',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'dev'::character varying"))
        batch_op.alter_column('send_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
