"""Add group trip and trip invite permissions fields

Revision ID: 370403a1d9f9
Revises: 515c867c7bc6
Create Date: 2025-12-23 04:31:30.206210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370403a1d9f9'
down_revision = '515c867c7bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ski_trip_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'accepted', 'declined', name='ski_trip_participant_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['ski_trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='unique_ski_trip_participant')
    )
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_invites_allowed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_group_trip', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('is_group_trip')

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('trip_invites_allowed')

    op.drop_table('ski_trip_participant')
    # ### end Alembic commands ###
