"""add_resort_pass_table

Revision ID: 3c7a73531f33
Revises: 272f5f30536f
Create Date: 2026-04-20 16:15:12.360798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7a73531f33'
down_revision = '272f5f30536f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resort_pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resort_id', sa.Integer(), nullable=False),
    sa.Column('pass_name', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resort_id'], ['resort.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resort_id', 'pass_name', name='uq_resort_pass')
    )
    with op.batch_alter_table('resort_pass', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resort_pass_resort_id'), ['resort_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort_pass', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resort_pass_resort_id'))

    op.drop_table('resort_pass')
    # ### end Alembic commands ###
