"""Add home_resort_id and visited_resort_ids columns

Revision ID: 3da15843eb30
Revises: e1c61ef6913c
Create Date: 2025-12-22 19:07:37.495093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da15843eb30'
down_revision = 'e1c61ef6913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_resort_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visited_resort_ids', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'resort', ['home_resort_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visited_resort_ids')
        batch_op.drop_column('home_resort_id')

    # ### end Alembic commands ###
