"""Update InviteToken model for reusable tokens

Revision ID: 443a306ca9ad
Revises: 5d9dceb7b16a
Create Date: 2025-12-12 03:13:01.057059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443a306ca9ad'
down_revision = '5d9dceb7b16a'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add new columns as nullable first
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inviter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_uses', sa.Integer(), nullable=True))

    # Step 2: Migrate data from inviter_user_id to inviter_id
    op.execute("UPDATE invite_token SET inviter_id = inviter_user_id WHERE inviter_user_id IS NOT NULL")
    
    # Step 3: Make inviter_id NOT NULL now that data is migrated
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.alter_column('inviter_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_invite_token_token'), ['token'], unique=True)
        batch_op.create_foreign_key(None, 'user', ['inviter_id'], ['id'])

    # Step 4: Drop old columns and constraints
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.drop_constraint('invite_token_inviter_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('invite_token_used_by_fkey', type_='foreignkey')
        batch_op.drop_column('used_by')
        batch_op.drop_column('inviter_user_id')
        batch_op.drop_column('used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inviter_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('used_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invite_token_used_by_fkey'), 'user', ['used_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('invite_token_inviter_user_id_fkey'), 'user', ['inviter_user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_invite_token_token'))
        batch_op.create_unique_constraint(batch_op.f('invite_token_token_key'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('max_uses')
        batch_op.drop_column('used_at')
        batch_op.drop_column('inviter_id')

    # ### end Alembic commands ###
