"""Add Activity model for friends feed

Revision ID: 44687c74df69
Revises: 623aa0522670
Create Date: 2025-12-26 20:47:48.205212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44687c74df69'
down_revision = '623aa0522670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
