"""add_backcountry_avi_previous_pass

Revision ID: 48e43cd3b3b9
Revises: f837033d3191
Create Date: 2026-04-12 12:28:58.355506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e43cd3b3b9'
down_revision = 'f837033d3191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backcountry_capable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('avi_certified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('previous_pass', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('previous_pass')
        batch_op.drop_column('avi_certified')
        batch_op.drop_column('backcountry_capable')

    # ### end Alembic commands ###
