"""Add invited_by_user_id column to User for durable inviter tracking

Revision ID: 4bce8428b800
Revises: 859082badfb5
Create Date: 2025-12-25 14:40:30.493345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bce8428b800'
down_revision = '859082badfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['invited_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invited_by_user_id')

    # ### end Alembic commands ###
