"""Add progressive profile completion fields

Revision ID: 515c867c7bc6
Revises: 3da15843eb30
Create Date: 2025-12-23 00:48:30.201074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '515c867c7bc6'
down_revision = '3da15843eb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('slot',
               existing_type=postgresql.ENUM('PRIMARY', 'SECONDARY', name='equipment_slot_enum'),
               nullable=True)
        batch_op.alter_column('discipline',
               existing_type=postgresql.ENUM('SKIER', 'SNOWBOARDER', name='equipment_discipline_enum'),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_riding_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('welcome_next_steps_shown_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('welcome_next_steps_shown_at')
        batch_op.drop_column('primary_riding_style')

    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.alter_column('discipline',
               existing_type=postgresql.ENUM('SKIER', 'SNOWBOARDER', name='equipment_discipline_enum'),
               nullable=False)
        batch_op.alter_column('slot',
               existing_type=postgresql.ENUM('PRIMARY', 'SECONDARY', name='equipment_slot_enum'),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('equipment_status')

    # ### end Alembic commands ###
