"""Add buddy_passes column to User

Revision ID: 5487fb874e9b
Revises: ad47f88f62d4
Create Date: 2026-01-05 07:09:27.722292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5487fb874e9b'
down_revision = 'ad47f88f62d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buddy_passes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('buddy_passes')

    # ### end Alembic commands ###
