"""add equipment_override to trip

Revision ID: 5ad569b22019
Revises: 2bc94005ffbe
Create Date: 2026-01-08 03:02:15.525514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad569b22019'
down_revision = '2bc94005ffbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_override', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.drop_column('equipment_override')

    # ### end Alembic commands ###
