"""Add home_mountain field to User

Revision ID: 5d9dceb7b16a
Revises: e2b469906aac
Create Date: 2025-12-12 02:44:54.093917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9dceb7b16a'
down_revision = 'e2b469906aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_mountain', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('home_mountain')

    # ### end Alembic commands ###
