"""add password reset fields to user model

Revision ID: 623aa0522670
Revises: 218e2db34714
Create Date: 2025-12-26 10:28:51.198409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623aa0522670'
down_revision = '218e2db34714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_password_reset_token'), ['password_reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_reset_token'))
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
