"""Add terrain_preferences to User

Revision ID: 63ab515662b7
Revises: 6fce84e81a9a
Create Date: 2025-12-18 05:21:28.886332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ab515662b7'
down_revision = '6fce84e81a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('terrain_preferences')

    # ### end Alembic commands ###
