"""Add equipment_status fields

Revision ID: 6fcb2aa39fe3
Revises: 311665898421
Create Date: 2025-12-19 01:34:55.205647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcb2aa39fe3'
down_revision = '311665898421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_equipment_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_status', sa.String(length=20), nullable=True))

    # No backfill - will be handled later or via UI defaults
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('equipment_status')

    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.drop_column('trip_equipment_status')

    # ### end Alembic commands ###
