"""Add wish_list_resorts and purchase_year

Revision ID: 6fce84e81a9a
Revises: 869edc7ca2b9
Create Date: 2025-12-18 03:57:10.196012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fce84e81a9a'
down_revision = '869edc7ca2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_year', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wish_list_resorts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wish_list_resorts')

    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.drop_column('purchase_year')

    # ### end Alembic commands ###
