"""Add GroupTrip, TripGuest, and EquipmentSetup models

Revision ID: 6ff61499c1dc
Revises: bca28575ed40
Create Date: 2025-12-17 03:20:28.708902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ff61499c1dc'
down_revision = 'bca28575ed40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Enum('PRIMARY', 'SECONDARY', name='equipment_slot_enum', create_constraint=True), nullable=False),
    sa.Column('discipline', sa.Enum('SKIER', 'SNOWBOARDER', name='equipment_discipline_enum', create_constraint=True), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('length_cm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot', name='unique_user_equipment_slot')
    )
    op.create_table('group_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('accommodation_status', sa.Enum('BOOKED', 'NOT_YET', 'STAYING_WITH_FRIENDS', name='accommodation_status_enum', create_constraint=True), nullable=True),
    sa.Column('transportation_status', sa.Enum('HAVE_TRANSPORT', 'NEED_TRANSPORT', 'NOT_SURE', name='transportation_status_enum', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACCEPTED', name='guest_status_enum', create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['group_trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='unique_trip_guest')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_guest')
    op.drop_table('group_trip')
    op.drop_table('equipment_setup')
    # ### end Alembic commands ###
