"""Add planning details flow fields

Revision ID: 730b51599368
Revises: 6fcb2aa39fe3
Create Date: 2025-12-19 02:58:15.107004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730b51599368'
down_revision = '6fcb2aa39fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.alter_column('trip_duration',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planning_details_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('planning_details_dismissed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('historical_passes_by_season', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('historical_passes_by_season')
        batch_op.drop_column('planning_details_dismissed_at')
        batch_op.drop_column('planning_details_completed_at')
        batch_op.drop_column('login_count')

    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.alter_column('trip_duration',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
