"""Add DismissedInsightCard model

Revision ID: 7c5811428ce0
Revises: 3c7a73531f33
Create Date: 2026-04-21 21:56:23.283687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5811428ce0'
down_revision = '3c7a73531f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_insight_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=64), nullable=False),
    sa.Column('card_key', sa.String(length=255), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_type', 'card_key', name='uq_dismissed_insight_card')
    )
    with op.batch_alter_table('dismissed_insight_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dismissed_insight_card_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dismissed_insight_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dismissed_insight_card_user_id'))

    op.drop_table('dismissed_insight_card')
    # ### end Alembic commands ###
