"""add_message_event_log

Revision ID: 7e24870bab12
Revises: b3d1e7f2a9c4
Create Date: 2026-05-08 21:57:37.938446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e24870bab12'
down_revision = 'b3d1e7f2a9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_event_log_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_event_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_event_log_delivery_status'), ['delivery_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_event_log_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_event_log_recipient_user_id'), ['recipient_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_event_log_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_event_log_event_name'))
        batch_op.drop_index(batch_op.f('ix_message_event_log_delivery_status'))
        batch_op.drop_index(batch_op.f('ix_message_event_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_event_log_category'))

    # ### end Alembic commands ###
