"""Add country_name_override to Resort model

Revision ID: 7ee129efc281
Revises: 5487fb874e9b
Create Date: 2026-01-05 07:57:40.642037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee129efc281'
down_revision = '5487fb874e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name_override', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.drop_column('country_name_override')

    # ### end Alembic commands ###
