"""Add binding_type, boot_brand, boot_flex to EquipmentSetup

Revision ID: 869edc7ca2b9
Revises: fe306bcefa9f
Create Date: 2025-12-17 19:15:46.459406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869edc7ca2b9'
down_revision = 'fe306bcefa9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('binding_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('boot_brand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('boot_flex', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.drop_column('boot_flex')
        batch_op.drop_column('boot_brand')
        batch_op.drop_column('binding_type')

    # ### end Alembic commands ###
