"""Add Resort model and resort_id to SkiTrip

Revision ID: 995e2fe1c99b
Revises: 443a306ca9ad
Create Date: 2025-12-12 03:24:06.179881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995e2fe1c99b'
down_revision = '443a306ca9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('invite_token_token_key'), type_='unique')

    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resort_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'resort', ['resort_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resort_id')

    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('invite_token_token_key'), ['token'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
