"""Add model and boot_model columns to equipment_setup

Revision ID: 9d47420ca1b6
Revises: c747cdb80425
Create Date: 2025-12-22 00:05:44.579957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d47420ca1b6'
down_revision = 'c747cdb80425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('boot_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_setup', schema=None) as batch_op:
        batch_op.drop_column('boot_model')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
