"""remove password reset token fields

Revision ID: 9d75b4184d5f
Revises: 44687c74df69
Create Date: 2025-12-27 10:00:31.814913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d75b4184d5f'
down_revision = '44687c74df69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_reset_token'))
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('password_reset_expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_user_password_reset_token'), ['password_reset_token'], unique=False)

    # ### end Alembic commands ###
