"""Add extra_data JSON column to Activity model

Revision ID: a6e9ba17a20c
Revises: 2743ba21a257
Create Date: 2025-12-31 18:07:42.890314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e9ba17a20c'
down_revision = '2743ba21a257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('extra_data')

    # ### end Alembic commands ###
