"""Add is_region column to Resort model

Revision ID: ac885fab4a64
Revises: 4bce8428b800
Create Date: 2025-12-25 22:08:21.479742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac885fab4a64'
down_revision = '4bce8428b800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_region', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.drop_column('is_region')

    # ### end Alembic commands ###
