"""Add buddy_passes_available to User

Revision ID: af6f62403e45
Revises: 7ee129efc281
Create Date: 2026-01-05 08:14:57.668511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6f62403e45'
down_revision = '7ee129efc281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buddy_passes_available', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('buddy_passes_available')

    # ### end Alembic commands ###
