"""Make is_region non-nullable with server default

Revision ID: b257ce551764
Revises: ac885fab4a64
Create Date: 2025-12-25 22:17:20.626882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b257ce551764'
down_revision = 'ac885fab4a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add server default, then make non-nullable
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.alter_column('is_region',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.alter_column('is_region',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
