"""Add state_full to Resort model

Revision ID: bca28575ed40
Revises: 995e2fe1c99b
Create Date: 2025-12-12 03:45:48.551453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca28575ed40'
down_revision = '995e2fe1c99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_full', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resort', schema=None) as batch_op:
        batch_op.drop_column('state_full')

    # ### end Alembic commands ###
