"""add_auth_provider_provider_id_updated_at_make_nullable

Revision ID: d027d767b00b
Revises: e06822b0550e
Create Date: 2026-04-17 02:01:47.427268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd027d767b00b'
down_revision = 'e06822b0550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # Backfill: all existing users are email-auth users
    op.execute("UPDATE \"user\" SET auth_provider = 'email' WHERE auth_provider IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
