"""noop check

Revision ID: e0cc70daa7c1
Revises: f837033d3191
Create Date: 2026-01-15 12:25:18.726349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cc70daa7c1'
down_revision = 'f837033d3191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('resort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('state_full', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('country_name_override', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=50), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.Column('pass_brands', sa.String(length=150), nullable=True),
    sa.Column('pass_brands_json', sa.JSON(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_region', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rider_type', sa.String(length=50), nullable=True),
    sa.Column('primary_rider_type', sa.String(length=50), nullable=True),
    sa.Column('secondary_rider_types', sa.JSON(), nullable=True),
    sa.Column('rider_types', sa.JSON(), nullable=True),
    sa.Column('pass_type', sa.String(length=100), nullable=True),
    sa.Column('profile_setup_complete', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('home_state', sa.String(length=50), nullable=True),
    sa.Column('skill_level', sa.String(length=50), nullable=True),
    sa.Column('gear', sa.String(length=200), nullable=True),
    sa.Column('home_mountain', sa.String(length=100), nullable=True),
    sa.Column('mountains_visited', sa.JSON(), nullable=True),
    sa.Column('home_resort_id', sa.Integer(), nullable=True),
    sa.Column('visited_resort_ids', sa.JSON(), nullable=True),
    sa.Column('open_dates', sa.JSON(), nullable=True),
    sa.Column('wish_list_resorts', sa.JSON(), nullable=True),
    sa.Column('terrain_preferences', sa.JSON(), nullable=True),
    sa.Column('equipment_status', sa.String(length=20), nullable=True),
    sa.Column('buddy_passes', sa.JSON(), nullable=True),
    sa.Column('buddy_passes_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=20), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('profile_completed_at', sa.DateTime(), nullable=True),
    sa.Column('first_connection_at', sa.DateTime(), nullable=True),
    sa.Column('first_trip_created_at', sa.DateTime(), nullable=True),
    sa.Column('is_seeded', sa.Boolean(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('email_opt_in', sa.Boolean(), nullable=True),
    sa.Column('email_transactional', sa.Boolean(), nullable=True),
    sa.Column('email_social', sa.Boolean(), nullable=True),
    sa.Column('email_digest', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('first_planning_timestamp', sa.DateTime(), nullable=True),
    sa.Column('planning_completed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('planning_dismissed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('historical_passes_by_season', sa.JSON(), nullable=True),
    sa.Column('primary_riding_style', sa.String(length=50), nullable=True),
    sa.Column('welcome_modal_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_resort_id'], ['resort.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dismissed_nudge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date_range_start', 'date_range_end', name='unique_dismissed_nudge')
    )
    op.create_table('equipment_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Enum('PRIMARY', 'SECONDARY', name='equipment_slot_enum', create_constraint=True), nullable=True),
    sa.Column('discipline', sa.Enum('SKIER', 'SNOWBOARDER', name='equipment_discipline_enum', create_constraint=True), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('length_cm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('binding_type', sa.String(length=50), nullable=True),
    sa.Column('boot_brand', sa.String(length=50), nullable=True),
    sa.Column('boot_model', sa.String(length=100), nullable=True),
    sa.Column('boot_flex', sa.Integer(), nullable=True),
    sa.Column('purchase_year', sa.Integer(), nullable=True),
    sa.Column('equipment_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot', name='unique_user_equipment_slot')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('environment', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_seeded', sa.Boolean(), nullable=True),
    sa.Column('trip_invites_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='unique_friendship')
    )
    op.create_table('group_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('accommodation_status', sa.Enum('BOOKED', 'NOT_YET', 'STAYING_WITH_FRIENDS', name='accommodation_status_enum', create_constraint=True), nullable=True),
    sa.Column('transportation_status', sa.Enum('HAVE_TRANSPORT', 'NEED_TRANSPORT', 'NOT_SURE', name='transportation_status_enum', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_token_token'), ['token'], unique=True)

    op.create_table('ski_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resort_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('mountain', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('pass_type', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('ride_intent', sa.String(length=20), nullable=True),
    sa.Column('trip_duration', sa.String(length=20), nullable=True),
    sa.Column('trip_equipment_status', sa.String(length=20), nullable=True),
    sa.Column('equipment_override', sa.String(length=20), nullable=True),
    sa.Column('accommodation_status', sa.String(length=20), nullable=True),
    sa.Column('accommodation_link', sa.String(length=500), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_group_trip', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resort_id'], ['resort.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.String(length=100), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('send_count', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('invite_type', sa.Enum('OUTBOUND', 'REQUEST', name='invite_type_enum', create_constraint=True), server_default='outbound', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['ski_trip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', 'trip_id', name='unique_invitation_per_trip')
    )
    op.create_table('ski_trip_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACCEPTED', 'DECLINED', name='ski_trip_participant_status_enum', create_constraint=True), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'GUEST', name='participant_role_enum', create_constraint=True), nullable=False),
    sa.Column('transportation_status', sa.Enum('DRIVING', 'FLYING', 'TRAIN', 'BUS', 'TBD', name='participant_transportation_enum', create_constraint=True), nullable=True),
    sa.Column('equipment_status', sa.Enum('OWN', 'RENTING', 'NEEDS_RENTALS', name='participant_equipment_enum', create_constraint=True), nullable=True),
    sa.Column('taking_lesson', sa.Enum('yes', 'no', 'maybe', name='lesson_choice_enum', create_constraint=True), server_default='no', nullable=False),
    sa.Column('carpool_role', sa.Enum('DRIVER', 'RIDER', 'DRIVER_WITH_SPACE', 'DRIVER_NO_SPACE', 'NEEDS_RIDE', 'NOT_CARPOOLING', 'OTHER', name='carpool_role_enum', create_constraint=True), nullable=True),
    sa.Column('carpool_seats', sa.Integer(), nullable=True),
    sa.Column('needs_ride', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['ski_trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='unique_ski_trip_participant')
    )
    op.create_table('trip_guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACCEPTED', 'DECLINED', name='guest_status_enum', create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['group_trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='unique_trip_guest')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_guest')
    op.drop_table('ski_trip_participant')
    op.drop_table('invitation')
    op.drop_table('email_log')
    op.drop_table('ski_trip')
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_token_token'))

    op.drop_table('invite_token')
    op.drop_table('group_trip')
    op.drop_table('friend')
    op.drop_table('event')
    op.drop_table('equipment_setup')
    op.drop_table('dismissed_nudge')
    op.drop_table('activity')
    op.drop_table('user')
    op.drop_table('resort')
    op.drop_table('country')
    # ### end Alembic commands ###
