"""add_primary_and_secondary_rider_types

Revision ID: e1c61ef6913c
Revises: 9d47420ca1b6
Create Date: 2025-12-22 17:37:02.814945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c61ef6913c'
down_revision = '9d47420ca1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_rider_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_rider_types', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secondary_rider_types')
        batch_op.drop_column('primary_rider_type')

    # ### end Alembic commands ###
