"""Add gear, mountains_visited, and skill_level to onboarding

Revision ID: e2b469906aac
Revises: f8a9ea07855d
Create Date: 2025-12-11 17:03:46.981439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b469906aac'
down_revision = 'f8a9ea07855d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gear', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mountains_visited', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mountains_visited')
        batch_op.drop_column('gear')

    # ### end Alembic commands ###
