"""Add ride_intent to SkiTrip

Revision ID: fe306bcefa9f
Revises: 6ff61499c1dc
Create Date: 2025-12-17 19:01:22.410963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe306bcefa9f'
down_revision = '6ff61499c1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: open_date table and invite_token.max_uses were legacy unused columns
    # that have been cleaned up. Open dates are now stored as JSON on User model.
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ride_intent', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ski_trip', schema=None) as batch_op:
        batch_op.drop_column('ride_intent')

    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_uses', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('open_date',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('open_date_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('open_date_pkey'))
    )
    # ### end Alembic commands ###
