COUNTRIES = {
  "AR": "Argentina",
  "AU": "Australia",
  "BG": "Bulgaria",
  "CA": "Canada",
  "CL": "Chile",
  "CZ": "Czech Republic",
  "DE": "Germany",
  "ES": "Spain",
  "FR": "France",
  "GL": "Greenland",
  "IS": "Iceland",
  "IT": "Italy",
  "JP": "Japan",
  "NZ": "New Zealand",
  "NO": "Norway",
  "PL": "Poland",
  "RO": "Romania",
  "SI": "Slovenia",
  "SK": "Slovakia",
  "SE": "Sweden",
  "CH": "Switzerland",
  "TR": "Turkey",
  "US": "United States",
  "XK": "Kosovo"
}
